### ISSUE TITLE
sortingview backend crashes with connection to kachery daemon error

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#114]
```
{'success': False, 'error': 'Error posting json: 403 Incorrect or invalid client authorization code.'}                                 [5/1638]
Unexpected error registering tasks with kachery daemon.                                                                                        
Will retry in 10 seconds                                                                                                                       
Connection to daemon has been restored                                                                                                         
Task requested: fetch_average_waveform.2 (pure-calculation)                                                                                    
{'success': False, 'error': 'Error posting json: 403 Incorrect or invalid client authorization code.'}                                         
WARNING: unexpected problem updating task status for task: fetch_average_waveform.2 (status=pending)                                           
HITHER JOBS: 2 pending; 0 queued; 0 running; 60 finished; 0 errored; 30 cache hits                                                             
Traceback (most recent call last):                                                                                                             
  File "/home/kacheryuser/miniconda3/envs/kachery-env/bin/sortingview-start-backend", line 6, in <module>                                      
    sortingview.start_backend_cli()                                                                                                            
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/click/core.py", line 1137, in __call__                       
    return self.main(*args, **kwargs)                                                                                                          
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/click/core.py", line 1062, in main                           
    rv = self.invoke(ctx)                                                                                                                      
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke                         
    return ctx.invoke(self.callback, **ctx.params)                                                                                             
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/click/core.py", line 763, in invoke                          
    return __callback(*args, **kwargs)                                                                                                         
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/backend/start_backend_cli.py", line 8, in start_b
ackend_cli                                                                                                                                     
    start_backend(channel=channel)                                                                                                             
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/backend/start_backend.py", line 14, in start_back
end                                
    kc.run_task_backend(                                               
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/task_backend/run_task_backend.py", line 32, in
 run_task_backend                  
    B.process_events()             
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/task_backend/TaskBackend.py", line 47, in proc
ess_events                         
    self._task_job_manager.process_events()                            
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/task_backend/TaskJobManager.py", line 59, in p
rocess_events                      
    hi.wait(0)                     
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/hither2/_job_manager.py", line 241, in wait
    global_job_manager.wait(timeout_sec)                               
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/hither2/_job_manager.py", line 148, in wait
    self._iterate()                
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/hither2/_job_manager.py", line 34, in _iterate
    _batch_check_job_cache(jobs_to_check)                              
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/hither2/_check_job_cache.py", line 30, in _batch_check_job_ca
che                                
    new_messages = kc.watch_for_new_messages(watches, wait_msec=0)                                                                             
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/main.py", line 235, in watch_for_new_messages
    return _watch_for_new_messages(subfeed_watches=subfeed_watches, wait_msec=wait_msec, signed=signed)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/_feeds.py", line 341, in _watch_for_new_messag
es                                 
    raise Exception(f'Unable to watch for new messages.')                                                                                      
Exception: Unable to watch for new messages.                           
Cleaning up parallel job handler                                       
Cleaning up parallel job handler  
```

**Comment by magland** [comment]
This particular problem should now be fixed in kachery-daemon >= 1.0.21
Please report any new issues
