### ISSUE TITLE
Cannot start sortingview backend

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#115]
```
(kachery-env) typhoon:~% sortingview-start-backend --channel franklab
Traceback (most recent call last):
  File "/home/kacheryuser/miniconda3/envs/kachery-env/bin/sortingview-start-backend", line 6, in <module>
    sortingview.start_backend_cli()
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/backend/start_backend_cli.py", line 8, in start_backend_cli
    start_backend(channel=channel)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/backend/start_backend.py", line 11, in start_backend
    from ..tasks import dummy
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/tasks/__init__.py", line 2, in <module>
    from .example_recording_sorting import *
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/tasks/example_recording_sorting.py", line 6, in <module>
    from sortingview.config import job_cache, job_handler
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/config/__init__.py", line 1, in <module>
    from .job_cache import job_cache
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/config/job_cache.py", line 3, in <module>
    job_cache = hi.JobCache(feed_name='sortingview-job-cache')
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/hither2/_job_cache.py", line 14, in __init__
    feed = kc.load_feed(feed_name, create=True)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/main.py", line 223, in load_feed
    return _load_feed(feed_name_or_uri=feed_name_or_uri, timeout_sec=timeout_sec, create=create)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/_feeds.py", line 321, in _load_feed
    feed_id = _get_feed_id(feed_name, create=create)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/_feeds.py", line 295, in _get_feed_id
    return _create_feed(feed_name)._feed_id
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/_feeds.py", line 266, in _create_feed
    raise Exception(f'Unable to create feed: {feed_name}')
Exception: Unable to create feed: sortingview-job-cache

```

**Comment by magland** [comment]
Is this an issue right now? Even when the daemon is running properly? @khl02007

**Comment by khl02007** [comment]
This happens when I try to restart the backend shortly after it crashes (while the daemon is running). Interestingly if I wait a bit and try again the backend starts up again...

**Comment by khl02007** [comment]
I have just upgraded the kachery daemon to 1.0.21 but this keeps happening - can't start sortingview backend

**Comment by magland** [comment]
Please upgrade to kachery-client >= 1.0.13 and give it another shot. @khl02007

**Comment by khl02007** [comment]
OK I think it's working now - feel free to close the issue. By the way, someone in our lab is using typhoon at the moment (taking up most of the CPU and RAM). Could some of the slowness be due to this?

**Comment by khl02007** [comment]
Getting this message now in sortingview backend

```
Exception in hi.wait(0)
Traceback (most recent call last):
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/task_backend/TaskJobManager.py", line 61, in process_events
    hi.wait(0)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/hither2/_job_manager.py", line 241, in wait
    global_job_manager.wait(timeout_sec)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/hither2/_job_manager.py", line 148, in wait
    self._iterate()
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/hither2/_job_manager.py", line 34, in _iterate
    _batch_check_job_cache(jobs_to_check)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/hither2/_check_job_cache.py", line 30, in _batch_check_job_cache
    new_messages = kc.watch_for_new_messages(watches, wait_msec=0)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/main.py", line 236, in watch_for_new_messages
    return _watch_for_new_messages(subfeed_watches=subfeed_watches, wait_msec=wait_msec, signed=signed)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/_feeds.py", line 352, in _watch_for_new_messages
    raise Exception(f'Unable to watch for new messages.')
Exception: Unable to watch for new messages.
```

**Comment by khl02007** [comment]
```
Using cached result for subsample_sorting (0.1.5)
Using cached result for subsample_sorting (0.1.5)
Using cached result for subsample_sorting (0.1.5)
HITHER JOBS: 0 pending; 0 queued; 0 running; 127 finished; 0 errored; 15 cache hits
Elapsed time for manage-finished-jobs: 1.623950481414795 sec
HITHER JOBS: 0 pending; 0 queued; 0 running; 130 finished; 0 errored; 15 cache hits
{'success': False, 'error': 'Error posting json: 403 Incorrect or invalid client authorization code.'}
Unexpected error registering tasks with kachery daemon.
Will retry in 10 seconds
{'success': False, 'error': 'Error posting json: 403 Incorrect or invalid client authorization code.'}
Unexpected error registering tasks with kachery daemon.
Will retry in 10 seconds
{'success': False, 'error': 'Error posting json: 403 Incorrect or invalid client authorization code.'}
Unexpected error registering tasks with kachery daemon.
Will retry in 10 seconds
Connection to daemon has been restored
```

**Comment by magland** [comment]
I think this is due to that same problem we were experiencing before: file getting written but not getting updated on the file system.

Please upgrade to kachery-daemon >= 1.0.22 and restart the daemon.

**Comment by magland** [comment]
Closing (please reopen if not resolved)
