### ISSUE TITLE
error when using LabBoxEphysRecordingExtractor and spikemetrics

### ISSUE THREAD

**Issue by lfrank** [magland/sortingview#134]
When trying to compute metrics using a LabBox recording extractor, I get a large number of errors like the first four lines and then the error below.

Traceback (most recent call last):
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/baseextractor.py", line 36, in __del__
    for memmap_obj in self._memmap_files:
AttributeError: 'LabboxEphysRecordingExtractor' object has no attribute '_memmap_files'

Elapsed time for computing quality metrics: 3.801612615585327 sec
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/loren/Src/NWB/spiketoolkit/spiketoolkit/postprocessing/postprocessing_tools.py", line 2000, in _extract_waveforms_one_chunk
    recording = se.load_extractor_from_dict(rec_arg)
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/extraction_tools.py", line 732, in load_extractor_from_dict
    return BaseExtractor.load_extractor_from_dict(d)
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/baseextractor.py", line 523, in load_extractor_from_dict
    extractor = _load_extractor_from_dict(d)
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/baseextractor.py", line 554, in _load_extractor_from_dict
    extractor = _load_extractor_from_dict(kwargs[k])
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/baseextractor.py", line 554, in _load_extractor_from_dict
    extractor = _load_extractor_from_dict(kwargs[k])
  File "/home/loren/Src/NWB/spikeextractors/spikeextractors/baseextractor.py", line 585, in _load_extractor_from_dict
    extractor = cls(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'arg'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/loren/Src/NWB/notebooks/spikesorting_test.py", line 98, in <module>
    main()
  File "/home/loren/Src/NWB/notebooks/spikesorting_test.py", line 84, in main
    SpikeSorting.populate([(SpikeSortingParameters & {'nwb_file_name' : nwb_file_name, 'sort_interval_name' : sort_interval_name,
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/datajoint/autopopulate.py", line 153, in populate
    make(dict(key))
  File "/home/loren/Src/NWB/nwb_datajoint/src/nwb_datajoint/common/common_spikesorting.py", line 620, in make
    metrics = SpikeSortingMetrics().compute_metrics(cluster_metrics_list_name, whitened_recording, sorting)
  File "/home/loren/Src/NWB/nwb_datajoint/src/nwb_datajoint/common/common_spikesorting.py", line 426, in compute_metrics
    return st.validation.compute_quality_metrics(sorting=sorting,
  File "/home/loren/Src/NWB/spiketoolkit/spiketoolkit/validation/quality_metrics.py", line 1216, in compute_quality_metrics
    md.compute_pca_scores(**kwargs)
  File "/home/loren/Src/NWB/spiketoolkit/spiketoolkit/validation/quality_metric_classes/metric_data.py", line 224, in compute_pca_scores
    pc_feature_ind = get_pca_metric_data(self._recording, self._sorting, **kwargs)
  File "/home/loren/Src/NWB/spiketoolkit/spiketoolkit/validation/quality_metric_classes/utils/validation_tools.py", line 101, in get_pca_metric_data
    spike_clusters_pca, pc_features, pc_feature_ind = _get_pca_metric_data(recording, sorting, **kwargs)
  File "/home/loren/Src/NWB/spiketoolkit/spiketoolkit/postprocessing/postprocessing_tools.py", line 1554, in _get_pca_metric_data
    pc_list, pca_idxs, pc_ind = compute_unit_pca_scores(recording, sorting, return_idxs=True, **kwargs)
  File "/home/loren/Src/NWB/spiketoolkit/spiketoolkit/postprocessing/postprocessing_tools.py", line 1065, in compute_unit_pca_scores
    waveforms, spike_index_list, channel_index_list = get_unit_waveforms(recording, sorting, unit_ids,
  File "/home/loren/Src/NWB/spiketoolkit/spiketoolkit/postprocessing/postprocessing_tools.py", line 269, in get_unit_waveforms
    unit_waveforms = Parallel(n_jobs=n_jobs, backend=joblib_backend)(
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
TypeError: __init__() missing 1 required positional argument: 'arg'

**Comment by magland** [comment]
Naively, try the following on the recording prior to trying to compute the metrics:

```python
setattr(recording, '_memmap_files', [])
```

If that doesn't work, could you please send a self-contained script that reproduces the issue? You can begin the example script with:

```
R, S = se.example_datasets.toy_example()
recording = sv.LabboxEphysRecordingExtractor.store_recording_h5(R)
...
```

**Comment by magland** [comment]
I believe this is resolved now by using the newer spikeinterface objects for the metrics calculations.
