### ISSUE TITLE
curation view doesn't load

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#7]
The workspace view doesn't show some info like number of channels:
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/9277197/123903515-b04f4580-d923-11eb-801a-c198a85bc1aa.png">
When I click the sorting it doesn't load:
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/9277197/123903565-c52bd900-d923-11eb-82b1-810021006b68.png">
The kachery daemon shows this message:
`21:48:53.731 Ably: Auth.requestToken(): token request signing call returned error; err = 'Request failed with status code 404'`

**Comment by magland** [comment]
Made some updates. Please update all python packages, restart your daemon and task backend. Then give it another shot.

**Comment by khl02007** [comment]
Now nothing shows up...
![image](https://user-images.githubusercontent.com/9277197/124025480-55f6c900-d9a5-11eb-94a3-fb6eeec59406.png)

I still get the Ably requestToken error. And when I tried updating kachery-daemon, sortingview etc it didn't look like there was a new pip release?

**Comment by magland** [comment]
Ah, I think i failed to deploy a new kachery-daemon. I'll try to do that by
tomorrow morning.

**Comment by magland** [comment]
Please try again after upgrading to latest kachery-daemon (should be 1.0.15)

**Comment by magland** [comment]
@khl02007, there was a bug in that one too... we are still testing. But you'll want to be at least on 1.0.16 of kachery-daemon now.

**Comment by khl02007** [comment]
I see. Just to let you know, it seems some columns do not load; also external metrics missing for some reason:
![image](https://user-images.githubusercontent.com/9277197/124194330-3d59e200-da7d-11eb-8bc3-9876779ec3bf.png)
The error message:
![image](https://user-images.githubusercontent.com/9277197/124194367-4ea2ee80-da7d-11eb-8532-7617a34db5b7.png)

Here is URL to the sorting: https://sortingview.vercel.app/workspace/sorting/R-e8fdd5668819/S-8146b051cac4?workspace=ea2f73008a91dfc039ad25c75d4e9ce21ab5b2c4179eae9a01e086fd170d351b&channel=franklab

**Comment by khl02007** [comment]
Hi @magland, here is another update:

It seems the columns now load, but the external metrics still don't show up and the task manager shows the error from the message above from fetch_unit_metrics.1. The error occurs when I click the unit table. Once this happens, the other jobs that were running (e.g. loading average waveforms) stop and the sortingview backend crashes with the following error message. 

```
Traceback (most recent call last):                                      [24/959]
  File "/home/kacheryuser/miniconda3/envs/kachery-env/bin/sortingview-start-back
end", line 6, in <module>                                                       
    sortingview.start_backend_cli()                                             
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-package
s/click/core.py", line 1137, in __call__                                        
    return self.main(*args, **kwargs)                                           
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-package
s/click/core.py", line 1062, in main                                            
    rv = self.invoke(ctx)                                                       
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-package
s/click/core.py", line 1404, in invoke                                          
    return ctx.invoke(self.callback, **ctx.params)                              
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-package
s/click/core.py", line 763, in invoke                                           
    return __callback(*args, **kwargs)                                          
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-package
s/sortingview/backend/start_backend_cli.py", line 8, in start_backend_cli       
    start_backend(channel=channel)                                              
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-package
s/sortingview/backend/start_backend.py", line 8, in start_backend               
    kc.run_task_backend(                                                        
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-package
s/kachery_client/task_backend/run_task_backend.py", line 32, in run_task_backend
    B.process_events()
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-package
s/kachery_client/task_backend/TaskBackend.py", line 47, in process_events
    self._task_job_manager.process_events()
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-package
s/kachery_client/task_backend/TaskJobManager.py", line 50, in process_events
    requested_task.update_status(status=job.status, error_message=error_message,
 result=result)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-package
s/kachery_client/task_backend/RequestedTask.py", line 35, in update_status
    _update_task_status(channel=self.registered_task_function.channel, task_id=s
elf.task_id, task_function_id=self._registered_task_function.task_function_id, t
ask_hash=self.task_hash, task_function_type=self.task_function_type, status=stat
us, result=result, error_message=error_message)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-package
s/kachery_client/task_backend/_update_task_status.py", line 39, in _update_task_
status
    raise Exception(f'Unable to update task status')
Exception: Unable to update task status
Cleaning up parallel job handler
Cleaning up parallel job handler
Cleaning up parallel job handler
Cleaning up parallel job handler
Cleaning up parallel job handler
Cleaning up parallel job handler
```

**Comment by magland** [comment]
Thanks for the report. Let's set up a time on Tuesday to troubleshoot (please email me if/when you are available)

**Comment by lfrank** [comment]
This may be related to some issues: there are a few warnings when the sortingview backend is started:

Warning: Hither function with name createjob_get_timeseries_segment is registered in two different files: /home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/gui/extensions/timeseries/timeseries.py /home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/labbox_ephys/misc/get_timeseries_segment.py
Warning: Hither function with name createjob_fetch_average_waveform_2 is registered in two different files: /home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/gui/extensions/averagewaveforms/AverageWaveformsView/fetch_average_waveforms_2.py /home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/labbox_ephys/extensions/averagewaveforms/AverageWaveformsView/fetch_average_waveforms_2.py
Warning: Hither function with name createjob_individual_cluster_features is registered in two different files: /home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/gui/extensions/clusters/clusters.py /home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/labbox_ephys/extensions/clusters/clusters.py
Warning: Hither function with name createjob_fetch_spike_amplitudes is registered in two different files: /home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/gui/extensions/spikeamplitudes/spikeamplitudes.py /home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/labbox_ephys/extensions/spikeamplitudes/spikeamplitudes.py

**Comment by lfrank** [comment]
And the output when it crashes:

`Traceback (most recent call last):
  File "/home/kacheryuser/miniconda3/envs/kachery-env/bin/sortingview-start-backend", line 6, in <module>
    sortingview.start_backend_cli()
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/backend/start_backend_cli.py", line 8, in start_backend_cli
    start_backend(channel=channel)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/sortingview/backend/start_backend.py", line 8, in start_backend
    kc.run_task_backend(
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/task_backend/run_task_backend.py", line 32, in run_task_backend
    B.process_events()
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/task_backend/TaskBackend.py", line 47, in process_events
    self._task_job_manager.process_events()
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/task_backend/TaskJobManager.py", line 50, in process_events
    requested_task.update_status(status=job.status, error_message=error_message, result=result)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/task_backend/RequestedTask.py", line 35, in update_status
    _update_task_status(channel=self.registered_task_function.channel, task_id=self.task_id, task_function_id=self._registered_task_function.task_function_id, task_hash=self.task_hash, task_function_type=self.task_function_type, status=status, result=result, error_message=error_message)
  File "/home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_client/task_backend/_update_task_status.py", line 39, in _update_task_status
    raise Exception(f'Unable to update task status')
`

**Comment by magland** [comment]
Please try upgrading the following python packages, then restart the daemon and task backend, and try again:

```
pip install --upgrade sortingview kachery-daemon kachery-client hither labbox-ephys
```

You should be at:
```
labbox_ephys >= 0.7.1
sortingview >= 0.2.11
hither >= 0.7.0
kachery-daemon >= 1.0.16
kachery-client >= 1.0.5
```

**Comment by magland** [comment]
@lfrank @khl02007. Regarding the external sorting unit metrics not showing up, I was not able to reproduce the problem on my end. After upgrading the python packages and indicated above, please confirm that adding example external unit metrics works by following the newly added instructions on the web app (should be same procedure as before). See screenshot:

![image](https://user-images.githubusercontent.com/3679296/124520587-dc9f1200-ddba-11eb-8e84-57955d8c0fa1.png)

**Comment by khl02007** [comment]
Hi @magland, in the process of upgrading the python packages and restarting kachery daemon, I got the following error. This has not happened before and we did not change the private key file.
```
+ exec kachery-daemon-node start --verbose 0 --auth-group kachery-users --kachery-hub-url https://kacheryhub.org --label franklab --owner kyuhyun9056@gmail.com
Passed signature test
Error: Invalid permissions for private key file: /stelmo/nwb/kachery-storage/private.pem
    at _loadKeypair (/home/kacheryuser/miniconda3/envs/kachery-env/lib/node_modules/kachery-daemon-node/dist/startDaemon.js:111:15)
    at Object.startDaemon [as default] (/home/kacheryuser/miniconda3/envs/kachery-env/lib/node_modules/kachery-daemon-node/dist/startDaemon.js:21:40)
    at Object.handler (/home/kacheryuser/miniconda3/envs/kachery-env/lib/node_modules/kachery-daemon-node/dist/cli.js:112:34)
Uncaught exception:  Error: Invalid permissions for private key file: /stelmo/nwb/kachery-storage/private.pem
    at _loadKeypair (/home/kacheryuser/miniconda3/envs/kachery-env/lib/node_modules/kachery-daemon-node/dist/startDaemon.js:111:15)
    at Object.startDaemon [as default] (/home/kacheryuser/miniconda3/envs/kachery-env/lib/node_modules/kachery-daemon-node/dist/startDaemon.js:21:40)
    at Object.handler (/home/kacheryuser/miniconda3/envs/kachery-env/lib/node_modules/kachery-daemon-node/dist/cli.js:112:34)
```

**Comment by magland** [comment]
Strange.  The private key file needs to be readable only by the owner. What are the linux permissions on private.pem? Could that have changed?

**Comment by lfrank** [comment]
For some reason the permissions on that file were set to rwxrwxrwx, so I set them to rwx——— and now it seems to work.
